name: CI

on:
  push:
    branches: 
      - master

jobs:
  publish:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2.0.0

    - name: Setup node
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '10.x'

    - name: installing dependencies
      run: npm ci

    - name: building
      run: npm run build
        
    - name: publish coverage
      uses: coverallsapp/github-action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
